version: '3'

services:
  db:
    container_name: ${DOCKER_ENV}_${DOCKER_PROJECT_NAME}_database
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data:rw
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - ${DOCKER_NETWORK_NAME}

  pgadmin:
    depends_on:
      db:
        condition: service_healthy
    container_name: ${DOCKER_ENV}_${DOCKER_PROJECT_NAME}_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - ${DOCKER_NETWORK_NAME}

  app:
    depends_on:
      db:
        condition: service_healthy
    container_name: ${DOCKER_ENV}_${DOCKER_PROJECT_NAME}_app
    image: ${DOCKER_PROJECT_NAME}:${DOCKER_ENV}
    ports:
      - ${APP_PORT}:80
    networks:
      - ${DOCKER_NETWORK_NAME}

volumes:
  dbdata:

networks:
  staging_sidtest_network:
    driver: bridge