FROM php:8.3-apache

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && \
    install-php-extensions pdo_pgsql intl xml

RUN curl -sSk https://getcomposer.org/installer | php -- --disable-tls && \
   mv composer.phar /usr/local/bin/composer

RUN apt update && apt install -yqq nodejs npm

COPY ../.. /var/www/
COPY docker/global/apache.conf /etc/apache2/sites-available/000-default.conf
RUN chmod -R 777 /var/www/

WORKDIR /var/www/

EXPOSE 80